# Generated by Django 4.1.4 on 2022-12-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('dni', models.IntegerField()),
                ('correo', models.CharField(max_length=200)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivo')),
            ],
        ),
    ]
