# Generated by Django 4.1.4 on 2022-12-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
