# Generated by Django 4.1.4 on 2022-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='dni',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
